import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Claim",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="flex flex-col justify-center items-center bg-[#1C1917] text-white h-screen overflow-hidden">
                {children}
            </body>
        </html>
    );
}
